First commit
NeowayLabs/go-tfidf pull request #1
Opened 2021-03-30 20:20 UTC by vavieira10

This lib implements TF-IDF algorithm in Go lang.

2021-03-30 20:55 UTC, josofm reviewed
Nice job

2021-03-30 20:55 UTC, josofm commented on .gitlab-ci.yml
> +    - make check
I think you don't need this file

2021-03-30 20:55 UTC, josofm commented on Makefile
> +	git push origin $(version)
I think you don't need this release

2021-03-30 20:55 UTC, josofm commented on README.md
> +# go-tfidf
Don't forget to explain how install this library

2021-03-30 20:55 UTC, josofm commented on go.mod
> +go 1.13
Mybe use go 1.16

2021-03-30 20:55 UTC, josofm commented on go_tfidf.go
> +		DocumentSeparator:          " ",
Maybe in the new method we could pass the `separator` . That makes sense?

2021-03-30 20:55 UTC, josofm commented on go_tfidf_test.go
> +}
What do you think about test the case that we talked about?

2021-03-30 21:03 UTC, silver472 commented on go_tfidf.go
> +		docTerms := strings.Split(strings.ToLower(doc), ti.DocumentSeparator)
Does this array len need to be validated?

2021-03-30 21:03 UTC, Silver472 commented on go_tfidf_test.go
> +func TestTfIdfWithCosineSimilarity(t *testing.T) {
This test is acting like an "integration test", and it's ok for it to be here. Could you test the other functions without this "flow", just in an unit form, if the function is successful and not only when it's invalid?

2021-03-30 21:59 UTC, matheusvill requested changes

2021-03-30 21:59 UTC, matheusvill commented on .gitlab-ci.yml
> +    - make check
You could integrate with Travis https://github.com/NeowayLabs/gootstrap/blob/master/.travis.yml

2021-03-30 21:59 UTC, matheusvill commented on Makefile
> +	git push origin $(version)
This release is important but the publish not

2021-03-30 21:59 UTC, matheusvill commented on README.md
> +# go-tfidf
And how to run the tests and how to use this lib

2021-03-30 21:59 UTC, matheusvill commented on go_tfidf_test.go
> +	assert.Equal(t, expected, ti.DocumentSeparator)
You need a method to get this like a GetSeparator and the attribute needs to be private

2021-03-30 21:59 UTC, matheusvill commented on go_tfidf_test.go
> +	err := ti.AddDocuments(inputDocuments)
Why AddDocuments instead of just pass as a parameter of the function

2021-03-30 21:59 UTC, matheusvill commented on go_tfidf_test.go
> +	actual, err := ti.CalculateQueryTfIdfForEveryDocument(inputQuery)
The lib already called tfidf maybe the method name must be something more clear

2021-03-30 21:59 UTC, matheusvill commented on go_tfidf_test.go
> +	actual, err := go_tfidf.CalculateQueryTfIdf(inputQuery, " ")
Same here

2021-03-30 21:59 UTC, matheusvill commented on similarity/similarity.go
> +package similarity
Why this is another package?

2021-03-30 21:59 UTC, matheusvill commented on go_tfidf.go
> +	return &TfIdf{
All theses attributes could be private

2021-03-30 23:37 UTC, vavieira10 commented on go_tfidf.go
> +		DocumentSeparator:          " ",
@josofm I think that usually, by the default, the separator is `" "`. I think that if the person who's using the lib want to change, they should use the `SetSeparator`. I made this because the Go languagem doesn't support default values for function parameters.

2021-03-31 03:41 UTC, ryukinix commented
LGTM

2021-03-31 12:20 UTC, julianogalgaro commented on go_tfidf.go
> +		DocumentSeparator:          " ",
Maybe since we have DocumentSeparator (and others) as public, we don't need the SetSeparator method :) @vavieira10

2021-03-31 12:59 UTC, julianogalgaro requested changes

2021-03-31 12:59 UTC, julianogalgaro commented on go_tfidf.go
> +	Documents                  []string
how these fields are used internally I think we could use them as private :) @vavieira10 

except DocumentSeparator, sometimes is more clear just use, but its ok have some specific method too :)  

```go
tfidf:=tfIdf.New()
tfidf.DocumentSeparator="a"
```

2021-03-31 12:59 UTC, julianogalgaro commented on go_tfidf.go
> +func CalculateQueryTfIdf(query string, separator string) ([]float64, error) {
maybe we could have some godoc in public methods to help who is using the lib to chose the methods. After we can add this project to https://pkg.go.dev, like: https://pkg.go.dev/github.com/Neowaylabs/jsondiff

2021-03-31 12:59 UTC, julianogalgaro commented on Dockerfile
> +FROM alpine:3.9 as base
I'm not sure if we need this file, just if we will have some cli for this lib

2021-03-31 12:59 UTC, julianogalgaro commented on Makefile
> +build: modcache imagedev
I think we don't need this makefile target, just if we will have some cmd/cli for this lib

2021-03-31 12:59 UTC, julianogalgaro commented on README.md
> +
another cool tool is https://goreportcard.com/ tag, which check some things and can show a badge on readme :) like: https://goreportcard.com/report/github.com/NeowayLabs/jsondiff

2021-03-31 12:59 UTC, julianogalgaro commented on similarity/similarity.go
> +	switch strings.ToLower(similarityFunction) {
should we have some cases here?

2021-03-31 12:59 UTC, julianogalgaro commented on helper/helper.go
> +		if !StringArrayContainsWord(uniqueWords, w) {
do you know if is common we have huge slices?  if yes, maybe we could avoid checking all the slice for each word using some auxiliary map and check by key. But it is just a suggestion :)

like:
```go
    keys := make(map[string]struct{})
    for _, v := range words {
        if _, exists := keys[v]; !exists {
            keys[entry] = struct{}{}
            //store in your output slice
        }
    }    
    //...

```

2021-03-31 12:59 UTC, julianogalgaro commented on .gitignore
> +.devimgbuild.logs
we can ignore coverage files too

```suggestion
.devimgbuild.logs
coverage.html
coverage.out
```

2021-03-31 13:00 UTC, vavieira10 commented on go_tfidf_test.go
> +}
@josofm As we discussed, I will test this in the service (internal) thats going to use this lib

2021-03-31 13:24 UTC, vavieira10 commented on similarity/similarity.go
> +	switch strings.ToLower(similarityFunction) {
@julianogalgaro By now we only need the Cosine similarity function, that is also generally used. I don't think it would be necessary for adding any more by now.

2021-03-31 13:28 UTC, vavieira10 commented on go_tfidf_test.go
> +	err := ti.AddDocuments(inputDocuments)
@matheusvill which function? the `go_tfidf.New()` ?

2021-03-31 14:58 UTC, vavieira10 commented on similarity/similarity.go
> +package similarity
@matheusvill Not only for code organlization and modularity, but also because there are other similarity functions. I only implemented Cosine, but more functions can be added later

2021-03-31 15:00 UTC, vavieira10 commented on go.mod
> +go 1.13
@josofm Done!

2021-03-31 15:02 UTC, vavieira10 commented on go_tfidf.go
> +		docTerms := strings.Split(strings.ToLower(doc), ti.DocumentSeparator)
@Silver472 Done!

2021-03-31 15:03 UTC, vavieira10 commented on go_tfidf_test.go
> +func TestTfIdfWithCosineSimilarity(t *testing.T) {
@Silver472 I added more individual tests for public functions. The private functions are tested indirectly by the other public functions

2021-03-31 16:55 UTC, vavieira10 commented on go_tfidf.go
> +		DocumentSeparator:          " ",
@julianogalgaro @josofm I made all `TfIdf` variables private and created Setter and Getters

2021-03-31 16:56 UTC, vavieira10 commented on go_tfidf_test.go
> +	assert.Equal(t, expected, ti.DocumentSeparator)
@matheusvill Done!

2021-03-31 16:57 UTC, vavieira10 commented on go_tfidf_test.go
> +	actual, err := ti.CalculateQueryTfIdfForEveryDocument(inputQuery)
@matheusvill I changed. What do you think now? I couldn't find a less descriptive name.

2021-03-31 16:57 UTC, vavieira10 commented on go_tfidf_test.go
> +	actual, err := go_tfidf.CalculateQueryTfIdf(inputQuery, " ")
@matheusvill I changed. What do you think now? I couldn't find a less descriptive name.

2021-03-31 16:58 UTC, vavieira10 commented on go_tfidf.go
> +	return &TfIdf{
@matheusvill Done!

2021-03-31 17:05 UTC, vavieira10 commented on go_tfidf.go
> +	Documents                  []string
@julianogalgaro Done!

2021-03-31 17:27 UTC, vavieira10 commented on helper/helper.go
> +		if !StringArrayContainsWord(uniqueWords, w) {
@julianogalgaro Thanks for the suggestion! Done!

2021-03-31 17:27 UTC, vavieira10 commented on .gitignore
> +.devimgbuild.logs
@julianogalgaro Done!

2021-03-31 17:32 UTC, vavieira10 commented on go_tfidf.go
> +	Documents                  []string
@julianogalgaro Done!

2021-03-31 18:05 UTC, josofm commented on .travis.yml
> +    - leonardo.borges@neoway.com.br
I think you could put juliano, you, vill and murilo here.

2021-03-31 18:16 UTC, josofm approved these changes

2021-04-01 12:14 UTC, LeoCBS commented on go_tfidf.go
> +	return &TfIdf{
why don't union function `AddDocuments` to this constructor? we can call other functions without call `AddDocuments`? @vavieira10

2021-04-01 12:14 UTC, LeoCBS commented on go_tfidf_test.go
> +	assert.Equal(t, expected, actual)
we need an import to testify just a simple comparison? testify is bloated to this case.. what do you think to create on test/assert.go with this comparison? @vavieira10

2021-04-01 12:14 UTC, LeoCBS commented on helper/helper.go
> +package helper
helper is one generic name.. maybe change to string helper.. could be more clear.. what do you think? @vavieira10

2021-04-01 15:37 UTC, vavieira10 commented on Makefile
> +	git push origin $(version)
@josofm Done!

2021-04-01 15:50 UTC, vavieira10 commented on helper/helper.go
> +package helper
@LeoCBS I created with this name, because it was supposed to be a package with generic functions. So I think, this name is ok. What do you think?

2021-04-01 18:13 UTC, vavieira10 commented on go_tfidf_test.go
> +	err := ti.AddDocuments(inputDocuments)
@matheusvill Added the AddDocuments for the TfIdf constructor. If someone has to add any other documents, simply can also use AddDocuments

2021-04-01 18:13 UTC, vavieira10 commented on Dockerfile
> +FROM alpine:3.9 as base
@julianogalgaro Removed!

2021-04-01 18:14 UTC, vavieira10 commented on Makefile
> +build: modcache imagedev
@julianogalgaro Removed!

2021-04-01 18:14 UTC, vavieira10 commented on .travis.yml
> +    - leonardo.borges@neoway.com.br
@josofm Done!

2021-04-01 18:14 UTC, vavieira10 commented on go_tfidf_test.go
> +	assert.Equal(t, expected, actual)
@LeoCBS I think its ok to use it. We also use in other internal libs.

2021-04-01 18:15 UTC, vavieira10 commented on helper/helper.go
> +package helper
@LeoCBS Just added to constructor!!

2021-04-13 13:21 UTC, julianogalgaro commented on README.md
> +separator := " "
I think will be nice we have all code to run, it helps the user copy, paste, and runs, what do you think? :) @vavieira10

2021-04-13 13:22 UTC, vavieira10 commented on README.md
> +# go-tfidf
@matheusvill @josofm Done!

2021-04-13 13:22 UTC, julianogalgaro commented on go_tfidf.go
> +	DocumentSeparator          string
maybe a doc for this public struct+field? @vavieira10

2021-04-13 13:46 UTC, vavieira10 commented on README.md
> +separator := " "
@julianogalgaro Done!

2021-04-13 13:46 UTC, vavieira10 commented on go_tfidf.go
> +	DocumentSeparator          string
@julianogalgaro Done!

2021-04-13 14:16 UTC, julianogalgaro approved these changes
nice!

2021-04-13 14:18 UTC, matheusvill approved these changes
Nice!

2021-04-16 12:21 UTC, LeoCBS commented on .travis.yml
> +    - tiago.katcipis@neoway.com.br
could you remove katcipis and kamila? @vavieira10

2021-04-16 12:22 UTC, LeoCBS commented on go_tfidf_test.go
> +	assert.Equal(t, expected, actual)
ok :)

2021-04-16 12:23 UTC, LeoCBS approved these changes

2021-04-16 12:23 UTC, LeoCBS commented
Nice

2021-04-16 12:26 UTC, vavieira10 commented on .travis.yml
> +    - tiago.katcipis@neoway.com.br
Done!

2021-04-16 12:42 UTC, Silver472 approved these changes
Nice!

2021-04-16 15:46 UTC, merged